In [1]:
import numpy as np


1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [2]:
a = np.array([1, 2, 3, 4, 5,6,7,8,9,10], dtype=float)

print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [3]:
m = np.zeros((3,3), dtype=int)

print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [4]:
m = np.random.randint(1,11, size=(5,5))

print(m)

[[ 5  5  1  4  2]
 [10  1  1  8  5]
 [ 9 10 10  3  1]
 [ 9 10  5  4  7]
 [ 8  9  4  7  6]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [5]:
m = np.random.rand(4,4)

print(m)

[[0.85010006 0.65658054 0.92344623 0.72214913]
 [0.81389612 0.96641158 0.31285585 0.86618322]
 [0.73979646 0.89042535 0.885005   0.2525073 ]
 [0.15014424 0.09617895 0.19897593 0.45429346]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [6]:
a = np.random.randint(1,11, size=(5))

print(a)

b = np.random.randint(1,11, size=(5))

print(b)

print(a + b)
print(a - b)
print(a * b)

[2 7 7 4 9]
[10  6  6  7  3]
[12 13 13 11 12]
[-8  1  1 -3  6]
[20 42 42 28 27]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [7]:
a = np.random.rand(7)

print("a=", a)

b = np.random.rand(7)

print("b=", b)

print(a * b)

a= [0.27248928 0.78657693 0.16237991 0.0474788  0.14052102 0.85747979
 0.74393968]
b= [0.8504122  0.0011795  0.70410639 0.41029036 0.88145021 0.69038346
 0.33012217]
[0.23172821 0.00092777 0.11433273 0.0194801  0.12386228 0.59198986
 0.24559098]


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [8]:
a = np.random.randint(1, 11, (2, 2))
print("A = ", a)
b = np.random.randint(1, 11, (2, 3))
print("B = ", b)
print("A * B = ", np.dot(a, b))

A =  [[6 7]
 [9 1]]
B =  [[6 6 2]
 [4 4 5]]
A * B =  [[64 64 47]
 [58 58 23]]


8. Cтворіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [9]:
a = np.random.randint(1, 11, (3, 3))
print("A = ", a)

a_inv = np.linalg.inv(a)
print("A^-1 = ", a_inv)

A =  [[ 8  6 10]
 [10  5  8]
 [ 1  4  1]]
A^-1 =  [[-0.22131148  0.27868852 -0.01639344]
 [-0.01639344 -0.01639344  0.29508197]
 [ 0.28688525 -0.21311475 -0.16393443]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [10]:
a = np.random.randint(1, 11, (4, 4))
print("A = ", a)

b = a.T
print("B =",b)

A =  [[ 6  3  1  7]
 [ 3 10  3  2]
 [ 8  2  2  8]
 [ 7  2  3  6]]
B = [[ 6  3  8  7]
 [ 3 10  2  2]
 [ 1  3  2  3]
 [ 7  2  8  6]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [11]:
m = np.random.randint(1, 11, size=(3, 4))
v = np.random.randint(1, 11, size=4)

print("M = ", m)
print("v = ", v)

print('M * v = ', np.dot(m, v))

M =  [[10  8  8  9]
 [ 4  6  4  7]
 [ 2 10  9  2]]
v =  [8 6 8 4]
M * v =  [228 128 156]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [12]:
m = np.random.rand(2, 3)
v = np.random.rand(3)

print("M = ", m)
print("v = ", v)

print('M * v = ', np.dot(m, v))

M =  [[0.19749877 0.44851262 0.05283868]
 [0.89049336 0.92800611 0.65846242]]
v =  [0.79409964 0.12646502 0.47164269]
M * v =  [0.23847584 1.13505975]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [13]:
A = np.random.randint(1, 11, size=(2, 2))
B = np.random.randint(1, 11, size=(2, 2))

print("A = ", A)
print("B = ", B)

print("A * B = ", A * B)

A =  [[10 10]
 [ 7  9]]
B =  [[5 8]
 [7 1]]
A * B =  [[50 80]
 [49  9]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [14]:
A = np.random.randint(1, 11, size=(2, 2))
B = np.random.randint(1, 11, size=(2, 2))

print("A = ", A)
print("B = ", B)

print("A * B = ", np.dot(A,B))

A =  [[3 5]
 [6 1]]
B =  [[ 3  5]
 [ 9 10]]
A * B =  [[54 65]
 [27 40]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [15]:
M = np.random.randint(1, 101, size=(5, 5))

print("M = ", M)

print("Msum = ",np.sum(M))

M =  [[35 30 88 90 11]
 [58 98 38 77 24]
 [46  9 32 96 76]
 [18 98  4 34 31]
 [43 70 83 36 73]]
Msum =  1298


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [16]:
A = np.random.randint(1, 11, size=(4, 4))
B = np.random.randint(1, 11, size=(4, 4))

print("A = ", A)
print("B = ", B)

print("A - B =", A-B)

A =  [[10  7 10  9]
 [ 9  7 10  5]
 [ 2  7 10  7]
 [ 7  5  1  8]]
B =  [[ 7  2  9  4]
 [10  1 10  2]
 [ 1  1  6 10]
 [10  6  6  9]]
A - B = [[ 3  5  1  5]
 [-1  6  0  3]
 [ 1  6  4 -3]
 [-3 -1 -5 -1]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [17]:
M = np.random.rand(5, 5)

print("M = ", M)

print("row_sum = ",(np.sum(M, axis=1, keepdims=True)))

M =  [[0.0963071  0.89608744 0.12971958 0.00672565 0.33332453]
 [0.62301704 0.91254197 0.81075598 0.35576368 0.35724767]
 [0.68791869 0.72820438 0.07306345 0.41921561 0.1517507 ]
 [0.22987175 0.44836989 0.13364249 0.39405667 0.21132295]
 [0.96708093 0.11469668 0.99716739 0.44631467 0.57967584]]
row_sum =  [[1.4621643 ]
 [3.05932634]
 [2.06015283]
 [1.41726374]
 [3.10493551]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [18]:
M = np.random.rand(3, 4)

print(" M original = ", M)

print("M squared = ", np.square(M))

 M original =  [[0.5579857  0.49593694 0.27002698 0.85739776]
 [0.99659198 0.31055644 0.05511842 0.00206587]
 [0.56310239 0.43081152 0.76900256 0.86752633]]
M squared =  [[3.11348038e-01 2.45953445e-01 7.29145679e-02 7.35130913e-01]
 [9.93195571e-01 9.64453018e-02 3.03804049e-03 4.26781342e-06]
 [3.17084297e-01 1.85598568e-01 5.91364933e-01 7.52601935e-01]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [19]:
v = np.random.randint(1, 51, size=4)

print("v = ", v)

print("v squared = ", np.sqrt(v))

v =  [22 15 43 47]
v squared =  [4.69041576 3.87298335 6.55743852 6.8556546 ]
